/**
 * MARD 拼豆色卡  —  根据官方色卡整理
 * 包含 A–M + H 共 9 个实色系列, 以及 P珠光/Q温变 特殊系列
 * hex 值为从色卡取色的近似值
 */
export const BEAD_PALETTES = {

  mard: {
    name: 'MARD 拼豆',
    colors: [
      // ═══════════ A 黄色系 ═══════════
      { code: 'A1',  name: '奶白',       hex: '#FFF8E1' },
      { code: 'A2',  name: '淡柠檬',     hex: '#FFF9C4' },
      { code: 'A3',  name: '柠檬黄',     hex: '#FFEE58' },
      { code: 'A4',  name: '鲜黄',       hex: '#FFD600' },
      { code: 'A5',  name: '琥珀黄',     hex: '#FFAB00' },
      { code: 'A6',  name: '深琥珀',     hex: '#FF8F00' },
      { code: 'A7',  name: '焦琥珀',     hex: '#EF6C00' },
      { code: 'A8',  name: '杏橙',       hex: '#FFAD42' },
      { code: 'A9',  name: '亮橙',       hex: '#E88A30' },
      { code: 'A10', name: '焦橙',       hex: '#D06020' },
      { code: 'A11', name: '鲜橙',       hex: '#FF7F00' },
      { code: 'A12', name: '红橙',       hex: '#CC4125' },
      { code: 'A13', name: '棕褐',       hex: '#8D6E63' },
      { code: 'A14', name: '奶黄',       hex: '#FFECB3' },
      { code: 'A15', name: '象牙',       hex: '#FFE4B5' },
      { code: 'A16', name: '暖白',       hex: '#FFFDE7' },
      { code: 'A17', name: '金黄',       hex: '#FFD54F' },
      { code: 'A18', name: '焦糖',       hex: '#B57030' },
      { code: 'A19', name: '深焦糖',     hex: '#9E6228' },
      { code: 'A20', name: '亮金',       hex: '#FFCA28' },
      { code: 'A21', name: '巧克力',     hex: '#6D4830' },
      { code: 'A22', name: '深巧克力',   hex: '#5C3D28' },
      { code: 'A23', name: '咖啡棕',     hex: '#503520' },
      { code: 'A24', name: '深咖啡',     hex: '#442D1A' },
      { code: 'A25', name: '极深棕',     hex: '#382515' },
      { code: 'A26', name: '黑棕',       hex: '#2E1E10' },

      // ═══════════ B 绿色系 ═══════════
      { code: 'B1',  name: '荧光绿',     hex: '#C6FF00' },
      { code: 'B2',  name: '亮黄绿',     hex: '#AEEA00' },
      { code: 'B3',  name: '草绿',       hex: '#64DD17' },
      { code: 'B4',  name: '鲜绿',       hex: '#4CAF50' },
      { code: 'B5',  name: '翠绿',       hex: '#43A047' },
      { code: 'B6',  name: '中绿',       hex: '#388E3C' },
      { code: 'B7',  name: '深绿',       hex: '#2E7D32' },
      { code: 'B8',  name: '墨绿',       hex: '#1B5E20' },
      { code: 'B9',  name: '森林绿',     hex: '#33691E' },
      { code: 'B10', name: '暗绿',       hex: '#194D19' },
      { code: 'B11', name: '橄榄绿',     hex: '#558B2F' },
      { code: 'B12', name: '黄绿',       hex: '#689F38' },
      { code: 'B13', name: '嫩绿',       hex: '#8BC34A' },
      { code: 'B14', name: '春绿',       hex: '#66BB6A' },
      { code: 'B15', name: '薄荷绿',     hex: '#81C784' },
      { code: 'B16', name: '浅薄荷',     hex: '#A5D6A7' },
      { code: 'B17', name: '粉绿',       hex: '#C8E6C9' },
      { code: 'B18', name: '湖绿',       hex: '#009688' },
      { code: 'B19', name: '浅湖绿',     hex: '#4DB6AC' },
      { code: 'B20', name: '淡湖绿',     hex: '#80CBC4' },
      { code: 'B21', name: '水绿',       hex: '#B2DFDB' },
      { code: 'B22', name: '鸭绿',       hex: '#00897B' },
      { code: 'B23', name: '深鸭绿',     hex: '#00695C' },
      { code: 'B24', name: '极深绿',     hex: '#004D40' },
      { code: 'B25', name: '青绿',       hex: '#26A69A' },
      { code: 'B26', name: '苹果绿',     hex: '#7CB342' },
      { code: 'B27', name: '芥末绿',     hex: '#827717' },
      { code: 'B28', name: '深橄榄',     hex: '#5D6B1A' },
      { code: 'B29', name: '军绿',       hex: '#4B5320' },
      { code: 'B30', name: '灰绿',       hex: '#6B8E5A' },
      { code: 'B31', name: '浅灰绿',     hex: '#94B576' },
      { code: 'B32', name: '淡灰绿',     hex: '#AED581' },

      // ═══════════ C 蓝色系 ═══════════
      { code: 'C1',  name: '冰蓝',       hex: '#E3F2FD' },
      { code: 'C2',  name: '淡天蓝',     hex: '#BBDEFB' },
      { code: 'C3',  name: '天蓝',       hex: '#90CAF9' },
      { code: 'C4',  name: '浅蓝',       hex: '#64B5F6' },
      { code: 'C5',  name: '亮蓝',       hex: '#42A5F5' },
      { code: 'C6',  name: '蓝',         hex: '#2196F3' },
      { code: 'C7',  name: '钴蓝',       hex: '#1E88E5' },
      { code: 'C8',  name: '深蓝',       hex: '#1565C0' },
      { code: 'C9',  name: '藏青蓝',     hex: '#0D47A1' },
      { code: 'C10', name: '海军蓝',     hex: '#1A237E' },
      { code: 'C11', name: '群青',       hex: '#283593' },
      { code: 'C12', name: '靛蓝',       hex: '#3949AB' },
      { code: 'C13', name: '宝蓝',       hex: '#3F51B5' },
      { code: 'C14', name: '矢车菊蓝',   hex: '#5C6BC0' },
      { code: 'C15', name: '薰衣草蓝',   hex: '#7986CB' },
      { code: 'C16', name: '浅薰蓝',     hex: '#9FA8DA' },
      { code: 'C17', name: '暗蓝',       hex: '#0D47A1' },
      { code: 'C18', name: '午夜蓝',     hex: '#1A1A6B' },
      { code: 'C19', name: '青蓝',       hex: '#0288D1' },
      { code: 'C20', name: '天青',       hex: '#03A9F4' },
      { code: 'C21', name: '浅天青',     hex: '#4FC3F7' },
      { code: 'C22', name: '粉蓝',       hex: '#81D4FA' },
      { code: 'C23', name: '水蓝',       hex: '#B3E5FC' },
      { code: 'C24', name: '蔚蓝',       hex: '#29B6F6' },
      { code: 'C25', name: '湖蓝',       hex: '#0277BD' },
      { code: 'C26', name: '深湖蓝',     hex: '#01579B' },
      { code: 'C27', name: '蓝灰',       hex: '#546E7A' },
      { code: 'C28', name: '深蓝灰',     hex: '#37474F' },
      { code: 'C29', name: '暗蓝灰',     hex: '#263238' },

      // ═══════════ D 紫色系 ═══════════
      { code: 'D1',  name: '淡紫',       hex: '#E1BEE7' },
      { code: 'D2',  name: '浅紫',       hex: '#CE93D8' },
      { code: 'D3',  name: '丁香紫',     hex: '#BA68C8' },
      { code: 'D4',  name: '兰花紫',     hex: '#AB47BC' },
      { code: 'D5',  name: '紫',         hex: '#9C27B0' },
      { code: 'D6',  name: '深紫',       hex: '#8E24AA' },
      { code: 'D7',  name: '暗紫',       hex: '#7B1FA2' },
      { code: 'D8',  name: '极暗紫',     hex: '#6A1B9A' },
      { code: 'D9',  name: '茄紫',       hex: '#4A148C' },
      { code: 'D10', name: '蓝紫',       hex: '#5E35B1' },
      { code: 'D11', name: '深蓝紫',     hex: '#4527A0' },
      { code: 'D12', name: '暗蓝紫',     hex: '#311B92' },
      { code: 'D13', name: '皇家紫',     hex: '#512DA8' },
      { code: 'D14', name: '浅蓝紫',     hex: '#7E57C2' },
      { code: 'D15', name: '粉紫',       hex: '#9575CD' },
      { code: 'D16', name: '淡粉紫',     hex: '#B39DDB' },
      { code: 'D17', name: '薰衣草',     hex: '#D1C4E9' },
      { code: 'D18', name: '玫瑰紫',     hex: '#E040FB' },
      { code: 'D19', name: '亮紫',       hex: '#D500F9' },
      { code: 'D20', name: '紫红',       hex: '#AA00FF' },
      { code: 'D21', name: '洋紫',       hex: '#C51162' },
      { code: 'D22', name: '暗洋紫',     hex: '#880E4F' },
      { code: 'D23', name: '深洋紫',     hex: '#6A0040' },
      { code: 'D24', name: '紫酱',       hex: '#4A0033' },
      { code: 'D25', name: '梅紫',       hex: '#7C1A8E' },
      { code: 'D26', name: '深梅紫',     hex: '#5A0068' },

      // ═══════════ E 肤色系 ═══════════
      { code: 'E1',  name: '瓷白',       hex: '#FFF5EE' },
      { code: 'E2',  name: '浅肤',       hex: '#FFE8D6' },
      { code: 'E3',  name: '淡肤',       hex: '#FFDAB9' },
      { code: 'E4',  name: '嫩肤',       hex: '#FFD0A8' },
      { code: 'E5',  name: '暖肤',       hex: '#FFC096' },
      { code: 'E6',  name: '蜜肤',       hex: '#F5B07A' },
      { code: 'E7',  name: '麦肤',       hex: '#E8A465' },
      { code: 'E8',  name: '古铜肤',     hex: '#D4944A' },
      { code: 'E9',  name: '深麦肤',     hex: '#C68642' },
      { code: 'E10', name: '棕肤',       hex: '#B07030' },
      { code: 'E11', name: '深棕肤',     hex: '#9A5E28' },
      { code: 'E12', name: '咖啡肤',     hex: '#8D5524' },
      { code: 'E13', name: '深咖啡肤',   hex: '#7A4820' },
      { code: 'E14', name: '巧克力肤',   hex: '#6B3A18' },
      { code: 'E15', name: '深巧克力肤', hex: '#5C3010' },
      { code: 'E16', name: '玫瑰肤',     hex: '#FFB5A0' },
      { code: 'E17', name: '粉肤',       hex: '#FFCCBC' },
      { code: 'E18', name: '杏肤',       hex: '#FFD8C0' },
      { code: 'E19', name: '驼色',       hex: '#D2B48C' },
      { code: 'E20', name: '暖驼色',     hex: '#C4A87A' },
      { code: 'E21', name: '深驼色',     hex: '#A68B5C' },
      { code: 'E22', name: '沙肤',       hex: '#E8D4B8' },
      { code: 'E23', name: '浅沙',       hex: '#F0E0CC' },
      { code: 'E24', name: '米肤',       hex: '#F5E6D0' },

      // ═══════════ F 红色系 ═══════════
      { code: 'F1',  name: '浅粉',       hex: '#FCE4EC' },
      { code: 'F2',  name: '淡粉',       hex: '#F8BBD0' },
      { code: 'F3',  name: '粉红',       hex: '#F48FB1' },
      { code: 'F4',  name: '玫粉',       hex: '#EC407A' },
      { code: 'F5',  name: '洋红',       hex: '#E91E63' },
      { code: 'F6',  name: '深洋红',     hex: '#C2185B' },
      { code: 'F7',  name: '品红',       hex: '#AD1457' },
      { code: 'F8',  name: '桃红',       hex: '#FF4081' },
      { code: 'F9',  name: '亮红',       hex: '#FF1744' },
      { code: 'F10', name: '正红',       hex: '#D32F2F' },
      { code: 'F11', name: '深红',       hex: '#C62828' },
      { code: 'F12', name: '暗红',       hex: '#B71C1C' },
      { code: 'F13', name: '枣红',       hex: '#8B1A1A' },
      { code: 'F14', name: '酒红',       hex: '#7B0D0D' },
      { code: 'F15', name: '珊瑚红',     hex: '#FF6F61' },
      { code: 'F16', name: '三文鱼',     hex: '#FA8072' },
      { code: 'F17', name: '浅珊瑚',     hex: '#FF8A80' },
      { code: 'F18', name: '西瓜红',     hex: '#EF5350' },
      { code: 'F19', name: '番茄红',     hex: '#E53935' },
      { code: 'F20', name: '砖红',       hex: '#C0392B' },
      { code: 'F21', name: '铁锈红',     hex: '#A02B1F' },
      { code: 'F22', name: '栗红',       hex: '#7F1D1D' },
      { code: 'F23', name: '黑红',       hex: '#5C1510' },
      { code: 'F24', name: '紫红',       hex: '#880E4F' },
      { code: 'F25', name: '深紫红',     hex: '#6A1039' },

      // ═══════════ G 松色系 ═══════════
      { code: 'G1',  name: '浅松',       hex: '#D8C8A8' },
      { code: 'G2',  name: '淡松',       hex: '#D0BF98' },
      { code: 'G3',  name: '暖米',       hex: '#C0AE88' },
      { code: 'G4',  name: '米棕',       hex: '#B0A078' },
      { code: 'G5',  name: '沙棕',       hex: '#A49468' },
      { code: 'G6',  name: '黄棕',       hex: '#988860' },
      { code: 'G7',  name: '深沙棕',     hex: '#887050' },
      { code: 'G8',  name: '松木棕',     hex: '#7A6040' },
      { code: 'G9',  name: '深松木',     hex: '#6C5438' },
      { code: 'G10', name: '核桃棕',     hex: '#604A30' },
      { code: 'G11', name: '深核桃',     hex: '#544028' },
      { code: 'G12', name: '栗棕',       hex: '#483820' },
      { code: 'G13', name: '黑棕',       hex: '#3A2E1E' },
      { code: 'G14', name: '奶茶',       hex: '#E0D0B4' },
      { code: 'G15', name: '浅卡其',     hex: '#D5C6A4' },
      { code: 'G16', name: '卡其',       hex: '#C4B494' },
      { code: 'G17', name: '深卡其',     hex: '#B4A282' },
      { code: 'G18', name: '暗卡其',     hex: '#9A8A6E' },
      { code: 'G19', name: '灰棕',       hex: '#7E7058' },
      { code: 'G20', name: '深灰棕',     hex: '#605040' },
      { code: 'G21', name: '暗灰棕',     hex: '#484038' },

      // ═══════════ H 灰色系 ═══════════
      { code: 'H1',  name: '灰黑',       hex: '#333333' },
      { code: 'H2',  name: '灰色',       hex: '#B0B0B0' },
      { code: 'H3',  name: '浅灰',       hex: '#D0D0D0' },
      { code: 'H4',  name: '银灰',       hex: '#C0C0C0' },
      { code: 'H5',  name: '中灰',       hex: '#9E9E9E' },
      { code: 'H6',  name: '深灰',       hex: '#707070' },
      { code: 'H7',  name: '暗灰',       hex: '#606060' },
      { code: 'H8',  name: '雪白',       hex: '#F5F5F5' },
      { code: 'H9',  name: '珍珠白',     hex: '#EEEEEE' },
      { code: 'H10', name: '烟灰',       hex: '#A0A0A0' },
      { code: 'H11', name: '铅灰',       hex: '#888888' },
      { code: 'H12', name: '石板灰',     hex: '#78909C' },
      { code: 'H13', name: '冷灰',       hex: '#90A4AE' },
      { code: 'H14', name: '暖灰',       hex: '#A89890' },
      { code: 'H15', name: '浅暖灰',     hex: '#C0B4A8' },
      { code: 'H16', name: '钢灰',       hex: '#6B6B6B' },
      { code: 'H17', name: '铁灰',       hex: '#505050' },
      { code: 'H18', name: '炭黑',       hex: '#2A2A2A' },
      { code: 'H19', name: '纯白',       hex: '#FFFFFF' },
      { code: 'H20', name: '象牙灰',     hex: '#E8E0D8' },
      { code: 'H21', name: '深炭灰',     hex: '#404040' },
      { code: 'H22', name: '墨灰',       hex: '#383838' },
      { code: 'H23', name: '纯黑',       hex: '#1A1A1A' },

      // ═══════════ M 暗色系 ═══════════
      { code: 'M1',  name: '暗蓝',       hex: '#0A2540' },
      { code: 'M2',  name: '暗紫',       hex: '#2D1B4E' },
      { code: 'M3',  name: '暗青',       hex: '#004040' },
      { code: 'M4',  name: '暗橄榄',     hex: '#2B3A1A' },
      { code: 'M5',  name: '暗棕',       hex: '#3E2215' },
      { code: 'M6',  name: '暗红棕',     hex: '#421515' },
      { code: 'M7',  name: '暗森林',     hex: '#1A3018' },
      { code: 'M8',  name: '暗藏青',     hex: '#1A1A40' },
      { code: 'M9',  name: '暗酒红',     hex: '#400D14' },
      { code: 'M10', name: '暗铁红',     hex: '#5A1818' },
      { code: 'M11', name: '暗墨绿',     hex: '#1A3A20' },
      { code: 'M12', name: '暗深蓝',     hex: '#102040' },
      { code: 'M13', name: '暗咖',       hex: '#302018' },
      { code: 'M14', name: '暗灰紫',     hex: '#382838' },
      { code: 'M15', name: '暗墨',       hex: '#1A2020' },

      // ═══════════ P 珠光系 ═══════════
      { code: 'P1',  name: '珠光白',     hex: '#F8F8FF' },
      { code: 'P2',  name: '珠光粉',     hex: '#FFE4E1' },
      { code: 'P3',  name: '珠光蓝',     hex: '#B0C4DE' },
      { code: 'P4',  name: '珠光绿',     hex: '#B0E0C8' },
      { code: 'P5',  name: '珠光紫',     hex: '#D8BFD8' },
      { code: 'P6',  name: '珠光金',     hex: '#FFE4B5' },
      { code: 'P7',  name: '珠光银',     hex: '#D8D8D8' },
      { code: 'P8',  name: '珠光红',     hex: '#FFB4B4' },
      { code: 'P9',  name: '珠光橙',     hex: '#FFDAB0' },
      { code: 'P10', name: '珠光黄',     hex: '#FAFAD2' },
      { code: 'P11', name: '珠光青',     hex: '#AFEEEE' },
      { code: 'P12', name: '珠光棕',     hex: '#CDAA7D' },
      { code: 'P13', name: '珠光灰',     hex: '#C0C0C0' },
      { code: 'P14', name: '珠光黑',     hex: '#3A3A3A' },
      { code: 'P15', name: '珠光玫红',   hex: '#FFB0C0' },
      { code: 'P16', name: '珠光玫紫',   hex: '#E0B0FF' },
      { code: 'P17', name: '珠光薰蓝',   hex: '#A6CAF0' },
      { code: 'P18', name: '珠光薄荷',   hex: '#A0E8C0' },
      { code: 'P19', name: '珠光湖蓝',   hex: '#87CEEB' },
      { code: 'P20', name: '珠光暖白',   hex: '#FFF8EA' },
      { code: 'P21', name: '珠光象牙',   hex: '#F5E8D0' },
      { code: 'P22', name: '珠光暗红',   hex: '#CD9B9B' },
      { code: 'P23', name: '珠光墨绿',   hex: '#7AB888' },

      // ═══════════ Q 温变系 ═══════════
      { code: 'Q1',  name: '温变粉',     hex: '#FFB6C1' },
      { code: 'Q2',  name: '温变蓝',     hex: '#87CEFA' },
      { code: 'Q3',  name: '温变紫',     hex: '#DDA0DD' },
      { code: 'Q4',  name: '温变绿',     hex: '#90EE90' },
      { code: 'Q5',  name: '温变橙',     hex: '#FFA07A' },
    ]
  },

  perler: {
    name: 'Perler Beads',
    colors: [
      { code: 'P01', name: 'White',          hex: '#F4F4F4' },
      { code: 'P02', name: 'Cream',          hex: '#F5E6C8' },
      { code: 'P03', name: 'Yellow',         hex: '#FFD800' },
      { code: 'P04', name: 'Orange',         hex: '#F58220' },
      { code: 'P05', name: 'Red',            hex: '#E4002B' },
      { code: 'P06', name: 'Bubblegum',      hex: '#F27DA0' },
      { code: 'P07', name: 'Purple',         hex: '#7B2D8E' },
      { code: 'P08', name: 'Dark Blue',      hex: '#003DA5' },
      { code: 'P09', name: 'Light Blue',     hex: '#69B3E7' },
      { code: 'P10', name: 'Dark Green',     hex: '#007A33' },
      { code: 'P11', name: 'Pearl Green',    hex: '#53B17F' },
      { code: 'P12', name: 'Brown',          hex: '#6C4B2A' },
      { code: 'P13', name: 'Grey',           hex: '#A7A8AA' },
      { code: 'P14', name: 'Black',          hex: '#231F20' },
      { code: 'P15', name: 'Rust',           hex: '#B33D26' },
      { code: 'P16', name: 'Light Brown',    hex: '#8B6F4E' },
      { code: 'P17', name: 'Peach',          hex: '#FFCBA4' },
      { code: 'P18', name: 'Tan',            hex: '#D2B48C' },
      { code: 'P19', name: 'Magenta',        hex: '#CE1485' },
      { code: 'P20', name: 'Neon Yellow',    hex: '#DFFF00' },
      { code: 'P21', name: 'Neon Orange',    hex: '#FF6700' },
      { code: 'P22', name: 'Neon Green',     hex: '#39FF14' },
      { code: 'P23', name: 'Neon Pink',      hex: '#FF6EC7' },
      { code: 'P24', name: 'Pastel Blue',    hex: '#AEC6CF' },
      { code: 'P25', name: 'Pastel Green',   hex: '#B2E0B2' },
      { code: 'P26', name: 'Pastel Lavender',hex: '#C5B9E8' },
      { code: 'P27', name: 'Pastel Yellow',  hex: '#FDFD96' },
      { code: 'P28', name: 'Pastel Pink',    hex: '#FFD1DC' },
      { code: 'P29', name: 'Cheddar',        hex: '#FFA600' },
      { code: 'P30', name: 'Toothpaste',     hex: '#B2DFDB' },
      { code: 'P31', name: 'Hot Coral',      hex: '#F7464A' },
      { code: 'P32', name: 'Plum',           hex: '#663046' },
      { code: 'P33', name: 'Kiwi Lime',      hex: '#8DB600' },
      { code: 'P34', name: 'Cyan',           hex: '#00BCD4' },
      { code: 'P35', name: 'Blueberry Cream',hex: '#4F86C6' },
      { code: 'P36', name: 'Periwinkle Blue',hex: '#6F72AF' },
      { code: 'P37', name: 'Light Pink',     hex: '#FFB3C1' },
      { code: 'P38', name: 'Bright Green',   hex: '#00C853' },
      { code: 'P39', name: 'Robin Egg Blue', hex: '#00CCCC' },
      { code: 'P40', name: 'Flamingo',       hex: '#EF7C8E' },
      { code: 'P41', name: 'Prickly Pear',   hex: '#A6D785' },
      { code: 'P42', name: 'Light Grey',     hex: '#C8C8C8' },
      { code: 'P43', name: 'Dark Grey',      hex: '#6E6E6E' },
      { code: 'P44', name: 'Sand',           hex: '#C2B280' },
      { code: 'P45', name: 'Butterscotch',   hex: '#E39B3F' },
      { code: 'P46', name: 'Fawn',           hex: '#C8A882' },
      { code: 'P47', name: 'Cherry',         hex: '#9B111E' },
      { code: 'P48', name: 'Cranapple',      hex: '#9B5B5B' },
    ]
  },

  hama: {
    name: 'Hama Beads',
    colors: [
      { code: 'H01', name: 'White',          hex: '#FFFFFF' },
      { code: 'H02', name: 'Cream',          hex: '#F6E6C5' },
      { code: 'H03', name: 'Yellow',         hex: '#FFE600' },
      { code: 'H04', name: 'Orange',         hex: '#F18A00' },
      { code: 'H05', name: 'Red',            hex: '#CC0033' },
      { code: 'H06', name: 'Pink',           hex: '#F06EAA' },
      { code: 'H07', name: 'Purple',         hex: '#6F2B91' },
      { code: 'H08', name: 'Blue',           hex: '#0054A6' },
      { code: 'H09', name: 'Light Blue',     hex: '#55A8DE' },
      { code: 'H10', name: 'Green',          hex: '#009640' },
      { code: 'H11', name: 'Light Green',    hex: '#5EBD3E' },
      { code: 'H12', name: 'Brown',          hex: '#6B3A2A' },
      { code: 'H13', name: 'Grey',           hex: '#9B9B9B' },
      { code: 'H14', name: 'Black',          hex: '#1A1A1A' },
      { code: 'H15', name: 'Claret',         hex: '#82202D' },
      { code: 'H16', name: 'Tan',            hex: '#C7A87C' },
      { code: 'H17', name: 'Flesh',          hex: '#F0C0A0' },
      { code: 'H18', name: 'Neon Yellow',    hex: '#CCFF00' },
      { code: 'H19', name: 'Neon Orange',    hex: '#FF6600' },
      { code: 'H20', name: 'Neon Red',       hex: '#FF0040' },
      { code: 'H21', name: 'Neon Pink',      hex: '#FF5ECD' },
      { code: 'H22', name: 'Neon Green',     hex: '#33FF00' },
      { code: 'H23', name: 'Pastel Yellow',  hex: '#FFF5A0' },
      { code: 'H24', name: 'Pastel Orange',  hex: '#FCB97D' },
      { code: 'H25', name: 'Pastel Pink',    hex: '#FFDEE0' },
      { code: 'H26', name: 'Pastel Purple',  hex: '#D5A0E0' },
      { code: 'H27', name: 'Pastel Blue',    hex: '#A0C8F0' },
      { code: 'H28', name: 'Pastel Green',   hex: '#A8E0B0' },
      { code: 'H29', name: 'Plum',           hex: '#663366' },
      { code: 'H30', name: 'Teddy Bear',     hex: '#B5651D' },
      { code: 'H31', name: 'Turquoise',      hex: '#00B4D8' },
      { code: 'H32', name: 'Dark Green',     hex: '#1B5E20' },
      { code: 'H33', name: 'Dark Grey',      hex: '#555555' },
      { code: 'H34', name: 'Raspberry',      hex: '#B91C6E' },
      { code: 'H35', name: 'Old Rose',       hex: '#C08081' },
      { code: 'H36', name: 'Azure',          hex: '#007FFF' },
      { code: 'H37', name: 'Olive',          hex: '#556B2F' },
      { code: 'H38', name: 'Light Pink',     hex: '#FFB6C1' },
      { code: 'H39', name: 'Bright Green',   hex: '#00AA00' },
      { code: 'H40', name: 'Gold',           hex: '#DAA520' },
      { code: 'H41', name: 'Ivory',          hex: '#FFFFF0' },
      { code: 'H42', name: 'Sand',           hex: '#C2B280' },
    ]
  }
};


export const DEFAULT_PALETTE_KEY = 'mard';
export const DEFAULT_BOARD_SIZE = 29;
